project:
  type: website
  output-dir: docs

website:
  title: "Afromapr 2025"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    logo: img/logo_cist_small.jpg
    contents:
      - href: index.qmd
        text: "A propos"
      - section: "DONNEES"
        contents:       
          - href: Data_001.qmd
            text: "Developpement des pays d'Afrique en 2018"  
          - href: Data_002.qmd
            text: "IDH infranational en Afrique de 1992 à 2022"               
      - section: "OBJECTIFS"
        contents:
          - href: Enseigne_R.qmd
            text: "Obj.1 Statistiques avec R"
          - href: Magrit.qmd
            text: "Obj.2 Cartographie avec Magrit"
          - href: Access.qmd
            text: "Obj.3 Accessibilité avec R et OSRM"
          - href: EnquetR.qmd
            text: "Obj.4 Enquêter avec R et Kobo"
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/afromapr
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2025, FR CIST
format:
  html:
    grid:
      sidebar-width: 300px
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


